### ISSUE TITLE
"Around the Web" Link Errors

### ISSUE THREAD

**Issue by panchr** [kirkstrobeck/whatismarkdown.com#9]
There is an issue with links in the "Around the Web" section. See the following screenshot of the console:

![image](https://cloud.githubusercontent.com/assets/6776539/4604481/20de8d90-51a1-11e4-9bc2-827fbcb5bf04.png)

This is in Chrome 37 for Windows.

**Comment by kirkstrobeck** [comment]
Thanks for the note! I believe this is resolved in https://github.com/kirkstrobeck/whatismarkdown.com/issues/15
